---
hamstack_openwebrx_enabled: false
hamstack_openwebrx_install: true
hamstack_openwebrx_image: jketterl/openwebrx:stable
hamstack_openwebrx_container_name: hamstack-openwebrx
hamstack_openwebrx_callsign: "{{ hamstack_callsign | default('N0CALL') }}"
hamstack_openwebrx_grid_locator: "{{ hamstack_grid_locator | default('') }}"
hamstack_openwebrx_receiver_device: ''
hamstack_openwebrx_device_mappings: []
hamstack_openwebrx_https_bind: 0.0.0.0
hamstack_openwebrx_https_port: 8444
hamstack_openwebrx_tls_host: "{{ inventory_hostname }}"
hamstack_openwebrx_caddy_image: caddy:2-alpine
hamstack_openwebrx_receiver_profiles: []
hamstack_openwebrx_data_dir: "{{ (hamstack_data_dir | default('/var/lib/hamstack')) ~ '/openwebrx' }}"
hamstack_openwebrx_autostart: true
hamstack_openwebrx_extra_settings: {}
