#!/usr/bin/env python3
"""Generate docs/variables.md from HamStack defaults and example site variables."""
from __future__ import annotations
import argparse
import json
import re
from pathlib import Path
from typing import Any
import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "variables.md"
CONFIG = ROOT / "docs" / "configuration.md"


def load_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return data if isinstance(data, dict) else {}


def md_value(value: Any) -> str:
    if isinstance(value, str):
        text = value
    elif value is None:
        text = "null"
    elif isinstance(value, bool):
        text = "true" if value else "false"
    elif isinstance(value, (int, float)):
        text = str(value)
    else:
        text = yaml.safe_dump(value, default_flow_style=True, sort_keys=False).strip()
    text = text.replace("|", "\\|").replace("\n", " ")
    if len(text) > 110:
        text = text[:107] + "..."
    return f"`{text}`"


def curated_purposes() -> dict[str, str]:
    purposes: dict[str, str] = {}
    if not CONFIG.exists():
        return purposes
    for line in CONFIG.read_text(encoding="utf-8").splitlines():
        if not line.startswith("| `hamstack_"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) >= 5:
            name = cells[0].strip("`")
            purposes[name] = cells[-1]
    return purposes


def infer_purpose(name: str, role: str) -> str:
    suffixes = [
        ("_enabled", f"Enable the {role} role/capability."),
        ("_install", "Allow HamStack to install the upstream software."),
        ("_autostart", "Enable/start the managed service or desktop autostart entry."),
        ("_extra_settings", "Reserved pass-through/extension settings not otherwise modeled."),
        ("_config_dir", "Configuration directory used by this role."),
        ("_data_dir", "Persistent data directory used by this role."),
        ("_bind_address", "Address on which the managed service binds."),
        ("_port", "Network port used by this setting."),
        ("_callsign", "Callsign used by this role."),
        ("_grid_locator", "Maidenhead grid locator used by this role."),
        ("_latitude", "Latitude used by this role when location is required."),
        ("_longitude", "Longitude used by this role when location is required."),
        ("_image", "Container image used by this role."),
        ("_container_name", "Container name managed by this role."),
        ("_version", "Requested upstream software version."),
        ("_package_url", "Explicit upstream package URL override."),
    ]
    for suffix, desc in suffixes:
        if name.endswith(suffix):
            return desc
    pretty = name.removeprefix("hamstack_").replace("_", " ")
    return f"Configuration value for {pretty}; see the {role} role README for operational context."


def collect() -> dict[str, list[tuple[str, Any, str]]]:
    groups: dict[str, list[tuple[str, Any, str]]] = {}
    site = load_yaml(ROOT / "inventory" / "example" / "group_vars" / "all.yml")
    groups["site/global"] = [(k, v, "inventory/example/group_vars/all.yml") for k, v in site.items() if k.startswith("hamstack_")]
    for defaults in sorted((ROOT / "roles").rglob("defaults/main.yml")):
        role = defaults.parent.parent.relative_to(ROOT / "roles").as_posix()
        data = load_yaml(defaults)
        groups[role] = [(k, v, defaults.relative_to(ROOT).as_posix()) for k, v in data.items() if k.startswith("hamstack_")]
    return groups


def render() -> str:
    purposes = curated_purposes()
    groups = collect()
    lines = [
        "# Complete HamStack variable index",
        "",
        "> Generated by `scripts/generate-variable-reference.py`. Do not edit this file by hand.",
        "",
        "This is the exhaustive index of `hamstack_*` variables currently declared by the tracked site example and role defaults. The hand-curated [configuration reference](configuration.md) and individual role READMEs explain the configuration model and higher-level behavior.",
        "",
    ]
    for role, entries in groups.items():
        if not entries:
            continue
        lines += [f"## `{role}`", "", "| Variable | Default | Purpose |", "| --- | --- | --- |"]
        for name, value, _source in sorted(entries):
            purpose = purposes.get(name) or infer_purpose(name, role)
            lines.append(f"| `{name}` | {md_value(value)} | {purpose} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if docs/variables.md is stale")
    args = parser.parse_args()
    generated = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != generated:
            print("docs/variables.md is stale; run scripts/generate-variable-reference.py")
            return 1
        print("docs/variables.md is current")
        return 0
    OUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
