---
hamstack_role_target: network_device
hamstack_openwrt_enabled: false
hamstack_network_hostname: ''
hamstack_network_vendor: ''
hamstack_network_model: ''
hamstack_network_lans: []
hamstack_network_wifi: []
hamstack_network_routes: []
hamstack_network_firewall_zones: []
hamstack_network_dns_servers: []
hamstack_network_apply_changes: true
hamstack_network_extra_settings: {}
